#!/bin/bash
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    # FACTS #######################################################################
    - name: "Set Known Facts"
      set_fact:
        pgrole: "pmm"
        image: "meisnate12/plex-meta-manager:latest"

    # LABELS ######################################################################
    - name: "Setting {{pgrole}} Volumes"
      set_fact:
        pg_volumes:
          - "/etc/localtime:/etc/localtime:ro"
          - "/opt/appdata/{{pgrole}}/app:/config"
          - "/opt/appdata/{{pgrole}}:/data"

    - name: "Setting {{pgrole}} ENV"
      set_fact:
        pg_env:
          PUID: "1000"
          PGID: "1000"
          PMM_TIME: "6:00"
          PMM_DIVIDER: "="
          PMM_WIDTH: "200"

    # MAIN DEPLOYMENT #############################################################
    - name: "Deploying {{pgrole}}"
      docker_container:
        name: "{{pgrole}}"
        image: "{{image}}"
        pull: yes
        volumes: "{{pg_volumes}}"
        env: "{{pg_env}}"
        restart_policy: unless-stopped
        networks:
          - name: plexguide
            aliases:
              - "{{pgrole}}"
        state: started
