#!/bin/bash
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    # FACTS #######################################################################
    - name: "Set Known Facts"
      set_fact:
        pgrole: "resilio"
        intport: "8888"
        extport: "8888"
        intport2: "55555"
        extport2: "55555"
        image: "ghcr.io/linuxserver/resilio-sync:latest"

    # CORE (MANDATORY) ############################################################
    - name: "Including cron job"
      include_tasks: "/opt/communityapps/apps/_core.yml"

    # LABELS ######################################################################
    - name: "Adding Traefik"
      set_fact:
        pg_labels:
          traefik.enable: "true"
          traefik.port: "{{intport}}"
          traefik.frontend.auth.forward.address: "http://authelia:9091/api/verify?rd=https://authelia.{{domain.stdout}}/"
          traefik.frontend.rule: "Host:{{pgrole}}.{{domain.stdout}}{{tldset}}{{cname}}"
          traefik.frontend.headers.SSLHost: "{{domain.stdout}}"
          traefik.frontend.headers.SSLRedirect: "true"
          traefik.frontend.headers.STSIncludeSubdomains: "true"
          traefik.frontend.headers.STSPreload: "true"
          traefik.frontend.headers.STSSeconds: "315360000"
          traefik.frontend.headers.browserXSSFilter: "true"
          traefik.frontend.headers.contentTypeNosniff: "true"
          traefik.frontend.headers.customResponseHeaders: "X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex"
          traefik.frontend.headers.forceSTSHeader: "true"

    - name: "Setting {{pgrole}} Volumes"
      set_fact:
        pg_volumes:
          - "/etc/localtime:/etc/localtime:ro"
          - "/opt/appdata/{{pgrole}}:/config"
          - "/mnt/downloads/resilio:/downloads"
          - "/mnt:/sync"

    - name: "Setting {{pgrole}} ENV"
      set_fact:
        pg_env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Europe/London"

    # MAIN DEPLOYMENT #############################################################
    - name: "Deploying {{pgrole}}"
      docker_container:
        name: "{{pgrole}}"
        image: "{{image}}"
        pull: yes
        published_ports:
          - "{{ports.stdout}}{{extport}}:{{intport}}"
          - "{{ports.stdout}}{{extport2}}:{{intport2}}"
        volumes: "{{pg_volumes}}"
        env: "{{pg_env}}"
        restart_policy: unless-stopped
        networks:
          - name: plexguide
            aliases:
              - "{{pgrole}}"
        state: started
        labels: "{{pg_labels}}"
